import Head from 'next/head';
import './globals.css';
import { M_PLUS_Rounded_1c } from 'next/font/google';

const inter = M_PLUS_Rounded_1c({ subsets: ['latin'], weight: '700' });

export const metadata = {
  title: 'Chinami ProfileSite',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ja'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
